version: '3.7'

services:
  db:
    image: mysql:8.0
    container_name: mysql # container's name
    ports:
      - 3307:3306 # outer port : inner port (port forwarding)
    environment:
      MYSQL_ROOT_PASSWORD: 'myPassword123'
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
